### PR TITLE
Fix EnsureObjective

### LINKED ISSUE #3483: Tearing down the with:peers test logs errors
When tearing down the with-peers tests we see[ errors in CI](https://app.circleci.com/pipelines/github/statechannels/statechannels/12595/workflows/63f45360-afe3-448c-8d6d-73f3fbd7c214/jobs/62054)

This seems to be due to the `handleMessage`  promise having a handle on the knex connection pool. When we call `destroy` on `knex` it results in an uncaught exception to be thrown which is caught and logged by `jest`.

### LINKED ISSUE #3510: Channels are still in turnNum:0 after a create Channel Objective Suceeded.
Even though the createchannels objectives succeed, calling `getChannels` afterwards results in channels that are not open.

This can be seen on this [branch](https://github.com/statechannels/statechannels/compare/ag/check-channel-results?expand=1).

Querying the database after the test runs returns `vars` for `server_wallet_a` with only one state:
```
[{"appData": "0x0abc", "isFinal": false, "outcome": {"type": "SimpleAllocation", "allocationItems": [{"amount": "0x01", "destination": "0x00000000000000000000000000000000000000000000000000000000000AaAa1"}, {"amount": "0x03", "destination": "0x00000000000000000000000000000000000000000000000000000000000BbBB2"}], "assetHolderAddress": "0x0000000000000000000000000000000000000000"}, "turnNum": 0, "stateHash": "0xe3cd4ef5f669b274c975e90f1e75cca32a4b8b12dc02a293d6688a2f5a6c9348", "signatures": [{"signer": "0xd480A7627C429CFA72354B376998Ad00f2c77BDD", "signature": "0xf7e4f05a384dabbd08c92545908d1989e3f8ecde5f347d42b14714aa50bdeae0459b66f431367e465b72971e597d560837568d914c794eed9465e036fa60d1701c"}]}]
```

### PR DESCRIPTION
**Pull request by lalexgap**
Fixes #3483. Fixes #3510.

# Description
This is a collection of fixes that are required to get `EnsureObjective` working properly.

1. A [fix](d8d86b6) for the objectiveId check on `objectiveSuceeded` that would always return true.
2. A [fix](6adf909) to the custom matcher so it prints out error results properly.
3. A small [enhancement](067b88c) to the ensure objective tests that checks the channel results.
4.  Some other minor fixes.

With these changes, we no longer see the `knex` errors from #3483 as we are actually waiting to get back an actual result from the `wallet`. Previously objective succeeded would be fired even if the objective had not suceeded.

### Code quality
- [x] I have written clear commit messages
- [x] I have performed a self-review of my own code
- [ ] This change does not have an unduly wide scope
- [x] I have separated logic changes from refactor changes (formatting, renames, etc.)
- [x] I have commented my code wherever necessary (can be 0)
- [x] I have added tests that prove my fix is effective or that my feature works, if necessary
### Project management
- [x] I have applied the [appropriate labels](https://www.notion.so/Team-working-agreements-2a95c926bb5642e5a5c42e4b74a9dd24#b304e56734a74dfbb341b8b4b27b1c0c)
- [x] I have [linked to all relevant issues](https://help.zenhub.com/support/solutions/articles/43000010350-connecting-pull-requests-to-github-issues) (can be 0)
- [x] I have [linked to all dependent issues](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies) (can be 0)
- [x] I have assigned myself to this PR
- [x] I have chosen the appropriate [pipeline](https://www.notion.so/Team-working-agreements-2a95c926bb5642e5a5c42e4b74a9dd24#d534e68e7edc46fe8a4cda61b2258c4e) on zenhub for the linked issue

### CODE REVIEW

File: packages/server-wallet/src/wallet/wallet.ts [hunk 1]
```diff
@@ -111,7 +111,7 @@ export class Wallet {
       let isComplete = false;
 
       const onObjectiveSucceeded = (o: WalletObjective) => {
-        if (o.objectiveId === o.objectiveId) {
+        if (objective.objectiveId === o.objectiveId) {
```
Comment (lalexgap) [inline packages/server-wallet/src/wallet/wallet.ts:114]: It looks like this flaw was copied from the original `ChannelManager` in the other repo.

File: packages/server-wallet/jest/custom-matchers.ts [hunk 2]
```diff
@@ -59,27 +59,30 @@ expect.extend({
...
+    const pass = received.length > 0 && doneResults.every(d => d.type === expected);
     if (pass) {
-      const matchingObjectives = received.filter(async o => (await o.done).type === expected);
+      const matchingObjectives = await printObjectives(
+        received.filter(async o => (await o.done).type === expected)
+      );
       return {
         pass,
         message: () =>
-          `expected every objective to not be ${expected}. Failing objectives: ${printObjectives(
```
Comment (kerzhner) [inline packages/server-wallet/jest/custom-matchers.ts:68]: Is this the correct message? Isn't this the condition for a valid pass?

**Review by kerzhner — APPROVED** [review]

File: packages/server-wallet/jest/custom-matchers.ts (hunk 2 above)
Comment (lalexgap) [reply packages/server-wallet/jest/custom-matchers.ts:68]: For the passing case, you return a `message` that would be used with `not`.
 IE : `expect(results).not.toHaveObjectiveDoneStatus('Success")` would return the `expected every objective to not be...` message.
