### PR TITLE
Fix pushMessage updating approved objective statuses to pending

### LINKED ISSUE #3523: PushMessage sets objective status to pending
**Describe the bug**

Currently the `PushMessage` function calls `ObjectiveModel.Insert` [on each objective it receives in a message](https://github.com/statechannels/statechannels/blob/3309bd2fc98e9026f90b156d7137f793aab01583/packages/server-wallet/src/engine/store.ts#L326:L326).

The `ObjectiveModel.Insert` has some upsert logic as seen [here](https://github.com/statechannels/statechannels/blob/ag/approve-o-api/packages/server-wallet/src/models/objective.ts#L196:L196):

```
  const model = await query
        .onConflict('objectiveId')
        .merge({status: preApproved ? 'approved' : 'pending'});
```

However, since we call `Objective.Insert` with `preApproved=false` (which is set [here](https://github.com/statechannels/statechannels/blob/3309bd2fc98e9026f90b156d7137f793aab01583/packages/server-wallet/src/engine/store.ts#L325)) that means the objective will be updated with a status of `pending` **even if it's already been approved**

I discovered this with the introduction of the `ApproveObjective` API. Now that participant B was calling `ensureObjectives` it meant that B was sending its objectives to A. When A received these objectives it would overwrite it's approved status with `pending`.

**To Reproduce**
This can be seen on the CI tests on https://github.com/statechannels/statechannels/pull/3485. If you disable database deletion after the tests run you can see that A's objectives are pending.

### PR DESCRIPTION
**Pull request by lalexgap**
# Description
Stops `PushMessage` from updating the status of approved objectives to pending.
Fixes #3523.

Before this PR the `pushMessage` on method on the `store` would call `ObjectiveModel.insert` on each objective it received in a message.

For every objective type besides `CloseChannel` `pushMessage` would call `ObjectiveModel.insert` with `preApprove` set to `false`.

This means that `ObjectiveModel.Insert` would update the status of approved objectives to pending.

The change in this PR is to switch from a `preApprove` boolean flag to an optional status argument: `approvalStatus?:'approved'|'pending'`. This allows us to only override the status if we intend to. Otherwise, it is left untouched.

It does seems like a code smell that we have a method called `insert` that's a partial `upsert` but I didn't want to increase the scope of this too much.

## How Has This Been Tested?
A test for the specific scenario was added in 4f9ae21

---
### Code quality
- [x] I have written clear commit messages
- [x] I have performed a self-review of my own code
- [x] This change does not have an unduly wide scope
- [x] I have separated logic changes from refactor changes (formatting, renames, etc.)
- [x] I have commented my code wherever necessary (can be 0)
- [x] I have added tests that prove my fix is effective or that my feature works, if necessary
### Project management
- [x] I have applied the [appropriate labels](https://www.notion.so/Team-working-agreements-2a95c926bb5642e5a5c42e4b74a9dd24#b304e56734a74dfbb341b8b4b27b1c0c)
- [x] I have [linked to all relevant issues](https://help.zenhub.com/support/solutions/articles/43000010350-connecting-pull-requests-to-github-issues) (can be 0)
- [x] I have [linked to all dependent issues](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies) (can be 0)
- [x] I have assigned myself to this PR
- [x] I have chosen the appropriate [pipeline](https://www.notion.so/Team-working-agreements-2a95c926bb5642e5a5c42e4b74a9dd24#d534e68e7edc46fe8a4cda61b2258c4e) on zenhub for the linked issue

### CODE REVIEW

File: packages/server-wallet/src/models/objective.ts [hunk 1]
```diff
@@ -191,9 +191,12 @@ export class ObjectiveModel extends Model {
         .returning('*')
         .first();
 
-      const model = await query
-        .onConflict('objectiveId')
-        .merge({status: preApproved ? 'approved' : 'pending'});
+      // Knex does not like properties with undefined values so we strip them out
+      const override = _.pickBy({status: approvalStatus, waitingFor}, _.identity);
+      // This allows for for the insert method to override the existing status or waitingFor if desired
+      const model = _.isEmpty(override)
```
Comment (kerzhner) [inline packages/server-wallet/src/models/objective.ts:197]: Curious, is the conditional necessary here? Does `const model = await query.onConflict('objectiveId').merge(override);` work with a empty `override` object?

File: packages/server-wallet/src/engine/__test__/integration/push-message.test.ts [hunk 2]
```diff
@@ -25,7 +27,7 @@ import {MultiThreadedEngine, Engine} from '../..';
 const dropNonVariables = (s: SignedState): any =>
   _.pick(s, 'appData', 'outcome', 'isFinal', 'turnNum', 'stateHash', 'signatures');
 
-jest.setTimeout(20_000);
```
Comment (kerzhner) [inline packages/server-wallet/src/engine/__test__/integration/push-message.test.ts:28]: Was this timeout increased while playing around with test? Or do we need the longer timeout?

File: packages/server-wallet/src/engine/__test__/integration/push-message.test.ts [hunk 3]
```diff
@@ -54,6 +56,36 @@ const four = 4;
...
+    participants: [],
+    data: {
+      targetChannelId: channelId,
+      fundingStrategy: 'Direct',
+      role: 'app',
+    },
+  };
+
+  const inserted = await ObjectiveModel.insert(objective, engine.knex, 'approved');
+  //Sanity check: We expect the objective to be approved since we used the preApproved flag
```
Comment (kerzhner) [inline packages/server-wallet/src/engine/__test__/integration/push-message.test.ts:76]: Nit
```suggestion
  //Sanity check: We expect the objective to be approved since we used the 'approved' parameter
```

File: packages/server-wallet/src/protocols/__test__/defunder.test.ts [hunk 4]
```diff
@@ -40,17 +40,17 @@ async function ensureCloseObjective(
...
   );
 }
 
 async function ensureDefundObjective(
   channel: TestChannel,
   tx: Transaction
 ): Promise<WalletObjective<DefundChannel>> {
-  // add a preapproved defundChannel objective and approve
-  return ObjectiveModel.insert(channel.defundChannelObjective(), true, tx);
+  // add a approved defundChannel objective and approve
```
Comment (kerzhner) [inline packages/server-wallet/src/protocols/__test__/defunder.test.ts:52]:
```suggestion
  // add an approved defundChannel objective and approve
```

File: packages/server-wallet/src/objectives/close-channel.ts [hunk 5]
```diff
@@ -23,8 +23,9 @@ export class CloseChannelObjective {
               txSubmitterOrder: [1, 0],
```
Comment (kerzhner) [inline packages/server-wallet/src/objectives/close-channel.ts:23]: Side note: It seems like the `CloseChannelObjective` does not use the shared `insert` method? Do you know if there is a reason for that?

**Review by kerzhner — APPROVED** [review]

File: packages/server-wallet/src/engine/__test__/integration/push-message.test.ts (hunk 2 above)
Comment (lalexgap) [reply packages/server-wallet/src/engine/__test__/integration/push-message.test.ts:28]: Ah, good catch. This was changed when I was originally investigating the issue and I forgot to modify it back.

File: packages/server-wallet/src/models/objective.ts (hunk 1 above)
Comment (lalexgap) [reply packages/server-wallet/src/models/objective.ts:197]: Yup, unfortunately `knex` fails when passed in an empty objective.
 ``` 
Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: objectives. 
```

File: packages/server-wallet/src/objectives/close-channel.ts (hunk 5 above)
Comment (lalexgap) [reply packages/server-wallet/src/objectives/close-channel.ts:23]: Doesn't `CloseChannelObjective` use the same `ObjectiveModel.Insert` that other code uses?

File: packages/server-wallet/src/engine/__test__/integration/push-message.test.ts (hunk 2 above)
Comment (lalexgap) [reply packages/server-wallet/src/engine/__test__/integration/push-message.test.ts]: b9cac13

File: packages/server-wallet/src/objectives/close-channel.ts (hunk 5 above)
Comment (kerzhner) [reply packages/server-wallet/src/objectives/close-channel.ts:23]: Yeah you are totally right. I misread this code.
